services:
  tappet:
    image: ghcr.io/gearboxlogic/tappet:latest
    pull_policy: always
    volumes:
      - ./config.docker.json:/config/config.json:ro
      - ./testdata/capabilities:/config/capabilities:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
